# Generated by Django 5.0.4 on 2024-05-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_product2db_alter_category2db_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2db',
            name='pcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
