# Generated by Django 5.0.4 on 2024-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webapp', '0002_registrationdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.IntegerField(blank=True, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Total_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
